name: 'dbt_ekom_analytics_capstone'
profile: 'dbt_ekom_analytics_capstone'
version: '1.0.0'
config-version: 2

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"  

clean-targets: ["target", "dbt_packages"]

seeds: {dbt_ekom_analytics_capstone: {+schema: landing}}

models:
  dbt_ekom_analytics_capstone:
    +materialized: table
    +database: "{{ target.catalog }}"
   # +pre-hook: "{{ audit_start() }}"
   # +post-hook: "{{ audit_end() }}"

    staging:      {+schema: bronze, +materialized: view}
    intermediate: {+schema: silver}
    mart:         {+schema: gold}

on-run-start: ["{{ audit_table_create() }}"]
on-run-end: ["{{ audit_table_log_run_results(results) }}"]

